# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: message.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
from google.protobuf import descriptor_pb2
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='message.proto',
  package='gocnn',
  syntax='proto3',
  serialized_pb=_b('\n\rmessage.proto\x12\x05gocnn\"\xd1\x01\n\tRequestV1\x12\x12\n\nboard_size\x18\x01 \x01(\x05\x12\x13\n\x0b\x62oard_state\x18\x02 \x03(\x08\x12\x16\n\x0eour_group_lib1\x18\x03 \x03(\x08\x12\x16\n\x0eour_group_lib2\x18\x04 \x03(\x08\x12\x1b\n\x13our_group_lib3_plus\x18\x05 \x03(\x08\x12\x17\n\x0foppo_group_lib1\x18\x06 \x03(\x08\x12\x17\n\x0foppo_group_lib2\x18\x07 \x03(\x08\x12\x1c\n\x14oppo_group_lib3_plus\x18\x08 \x03(\x08\"5\n\nResponseV1\x12\x12\n\nboard_size\x18\x01 \x01(\x05\x12\x13\n\x0bpossibility\x18\x02 \x03(\x02\"\xae\x03\n\tRequestV2\x12\x12\n\nboard_size\x18\x01 \x01(\x05\x12\x13\n\x0b\x62oard_state\x18\x02 \x03(\x08\x12\x16\n\x0eour_group_lib1\x18\x03 \x03(\x08\x12\x16\n\x0eour_group_lib2\x18\x04 \x03(\x08\x12\x16\n\x0eour_group_lib3\x18\x05 \x03(\x08\x12\x1b\n\x13our_group_lib4_plus\x18\x06 \x03(\x08\x12\x17\n\x0foppo_group_lib1\x18\x07 \x03(\x08\x12\x17\n\x0foppo_group_lib2\x18\x08 \x03(\x08\x12\x17\n\x0foppo_group_lib3\x18\t \x03(\x08\x12\x1c\n\x14oppo_group_lib4_plus\x18\n \x03(\x08\x12\x10\n\x08\x61ll_ones\x18\x0b \x03(\x08\x12\x14\n\x0cour_true_eye\x18\x0c \x03(\x08\x12\x14\n\x0cour_fake_eye\x18\r \x03(\x08\x12\x14\n\x0cour_semi_eye\x18\x0e \x03(\x08\x12\x15\n\roppo_true_eye\x18\x0f \x03(\x08\x12\x15\n\roppo_fake_eye\x18\x10 \x03(\x08\x12\x15\n\roppo_semi_eye\x18\x11 \x03(\x08\x12\x11\n\tall_zeros\x18\x12 \x03(\x08\"5\n\nResponseV2\x12\x12\n\nboard_size\x18\x01 \x01(\x05\x12\x13\n\x0bpossibility\x18\x02 \x03(\x02\x62\x06proto3')
)
_sym_db.RegisterFileDescriptor(DESCRIPTOR)




_REQUESTV1 = _descriptor.Descriptor(
  name='RequestV1',
  full_name='gocnn.RequestV1',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='board_size', full_name='gocnn.RequestV1.board_size', index=0,
      number=1, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='board_state', full_name='gocnn.RequestV1.board_state', index=1,
      number=2, type=8, cpp_type=7, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='our_group_lib1', full_name='gocnn.RequestV1.our_group_lib1', index=2,
      number=3, type=8, cpp_type=7, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='our_group_lib2', full_name='gocnn.RequestV1.our_group_lib2', index=3,
      number=4, type=8, cpp_type=7, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='our_group_lib3_plus', full_name='gocnn.RequestV1.our_group_lib3_plus', index=4,
      number=5, type=8, cpp_type=7, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='oppo_group_lib1', full_name='gocnn.RequestV1.oppo_group_lib1', index=5,
      number=6, type=8, cpp_type=7, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='oppo_group_lib2', full_name='gocnn.RequestV1.oppo_group_lib2', index=6,
      number=7, type=8, cpp_type=7, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='oppo_group_lib3_plus', full_name='gocnn.RequestV1.oppo_group_lib3_plus', index=7,
      number=8, type=8, cpp_type=7, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=25,
  serialized_end=234,
)


_RESPONSEV1 = _descriptor.Descriptor(
  name='ResponseV1',
  full_name='gocnn.ResponseV1',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='board_size', full_name='gocnn.ResponseV1.board_size', index=0,
      number=1, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='possibility', full_name='gocnn.ResponseV1.possibility', index=1,
      number=2, type=2, cpp_type=6, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=236,
  serialized_end=289,
)


_REQUESTV2 = _descriptor.Descriptor(
  name='RequestV2',
  full_name='gocnn.RequestV2',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='board_size', full_name='gocnn.RequestV2.board_size', index=0,
      number=1, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='board_state', full_name='gocnn.RequestV2.board_state', index=1,
      number=2, type=8, cpp_type=7, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='our_group_lib1', full_name='gocnn.RequestV2.our_group_lib1', index=2,
      number=3, type=8, cpp_type=7, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='our_group_lib2', full_name='gocnn.RequestV2.our_group_lib2', index=3,
      number=4, type=8, cpp_type=7, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='our_group_lib3', full_name='gocnn.RequestV2.our_group_lib3', index=4,
      number=5, type=8, cpp_type=7, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='our_group_lib4_plus', full_name='gocnn.RequestV2.our_group_lib4_plus', index=5,
      number=6, type=8, cpp_type=7, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='oppo_group_lib1', full_name='gocnn.RequestV2.oppo_group_lib1', index=6,
      number=7, type=8, cpp_type=7, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='oppo_group_lib2', full_name='gocnn.RequestV2.oppo_group_lib2', index=7,
      number=8, type=8, cpp_type=7, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='oppo_group_lib3', full_name='gocnn.RequestV2.oppo_group_lib3', index=8,
      number=9, type=8, cpp_type=7, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='oppo_group_lib4_plus', full_name='gocnn.RequestV2.oppo_group_lib4_plus', index=9,
      number=10, type=8, cpp_type=7, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='all_ones', full_name='gocnn.RequestV2.all_ones', index=10,
      number=11, type=8, cpp_type=7, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='our_true_eye', full_name='gocnn.RequestV2.our_true_eye', index=11,
      number=12, type=8, cpp_type=7, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='our_fake_eye', full_name='gocnn.RequestV2.our_fake_eye', index=12,
      number=13, type=8, cpp_type=7, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='our_semi_eye', full_name='gocnn.RequestV2.our_semi_eye', index=13,
      number=14, type=8, cpp_type=7, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='oppo_true_eye', full_name='gocnn.RequestV2.oppo_true_eye', index=14,
      number=15, type=8, cpp_type=7, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='oppo_fake_eye', full_name='gocnn.RequestV2.oppo_fake_eye', index=15,
      number=16, type=8, cpp_type=7, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='oppo_semi_eye', full_name='gocnn.RequestV2.oppo_semi_eye', index=16,
      number=17, type=8, cpp_type=7, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='all_zeros', full_name='gocnn.RequestV2.all_zeros', index=17,
      number=18, type=8, cpp_type=7, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=292,
  serialized_end=722,
)


_RESPONSEV2 = _descriptor.Descriptor(
  name='ResponseV2',
  full_name='gocnn.ResponseV2',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='board_size', full_name='gocnn.ResponseV2.board_size', index=0,
      number=1, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='possibility', full_name='gocnn.ResponseV2.possibility', index=1,
      number=2, type=2, cpp_type=6, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=724,
  serialized_end=777,
)

DESCRIPTOR.message_types_by_name['RequestV1'] = _REQUESTV1
DESCRIPTOR.message_types_by_name['ResponseV1'] = _RESPONSEV1
DESCRIPTOR.message_types_by_name['RequestV2'] = _REQUESTV2
DESCRIPTOR.message_types_by_name['ResponseV2'] = _RESPONSEV2

RequestV1 = _reflection.GeneratedProtocolMessageType('RequestV1', (_message.Message,), dict(
  DESCRIPTOR = _REQUESTV1,
  __module__ = 'message_pb2'
  # @@protoc_insertion_point(class_scope:gocnn.RequestV1)
  ))
_sym_db.RegisterMessage(RequestV1)

ResponseV1 = _reflection.GeneratedProtocolMessageType('ResponseV1', (_message.Message,), dict(
  DESCRIPTOR = _RESPONSEV1,
  __module__ = 'message_pb2'
  # @@protoc_insertion_point(class_scope:gocnn.ResponseV1)
  ))
_sym_db.RegisterMessage(ResponseV1)

RequestV2 = _reflection.GeneratedProtocolMessageType('RequestV2', (_message.Message,), dict(
  DESCRIPTOR = _REQUESTV2,
  __module__ = 'message_pb2'
  # @@protoc_insertion_point(class_scope:gocnn.RequestV2)
  ))
_sym_db.RegisterMessage(RequestV2)

ResponseV2 = _reflection.GeneratedProtocolMessageType('ResponseV2', (_message.Message,), dict(
  DESCRIPTOR = _RESPONSEV2,
  __module__ = 'message_pb2'
  # @@protoc_insertion_point(class_scope:gocnn.ResponseV2)
  ))
_sym_db.RegisterMessage(ResponseV2)


# @@protoc_insertion_point(module_scope)
